In [7]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

In [8]:
# Impor the OpenWeatherMap API key
from api_keys import weather_api_key

In [26]:
# List of cities
cities = ['Halifax', 'Québec', 'Montréal', 'Ottawa',
       'Gatineau', 'Toronto', 'Hamilton',
       'St. Catharines', 'Kitchener',
       'London', 'Windsor', 'Winnipeg', 'Calgary', 'Edmonton',
       'Vancouver']

In [27]:
# Set the API base URL
url = "http://api.openweathermap.org/data/2.5/weather?q=" 

#https://api.openweathermap.org/data/2.5/weather?q={city name},{country code}&appid={API key}

# Define an empty list to fetch the weather data for each city
city_data = []

# Print to logger
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters
record_count = 1
set_count = 1

# Loop through all the cities in our list to fetch weather data
for i, city in enumerate(cities):
        
    # Group cities in sets of 50 for logging purposes
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 0

    # Create endpoint URL with each city
    #city_url = f"{url}appid={weather_api_key}&q={city}&units=metric"
    city_url = f"{url}{city},CA&appid={weather_api_key}"
        
    # Log the url, record, and set numbers
    print("Processing Record %s of Set %s | %s" % (record_count, set_count, city))

    # Add 1 to the record count
    record_count += 1

    # Run an API request for each of the cities
    try:
        # Parse the JSON and retrieve data
        response_json = requests.get(city_url).json()
        #json.dumps(response_json, indent=4, sort_keys=True)
        #city_weather = response_json["weather"]
        
        # Parse out latitude, longitude, max temp, humidity, cloudiness, wind speed, country, and date
        city_lat = response_json["coord"]["lat"]
        city_lng = response_json["coord"]["lon"]
        city_max_temp = response_json["main"]["temp_max"]
        city_humidity = response_json["main"]["humidity"]
        city_clouds = response_json["clouds"]["all"]
        city_wind = response_json["wind"]["speed"]
        city_country = response_json["sys"]["country"]
        city_date = response_json["dt"]
      

        # Append the City information into city_data list
        city_data.append({"City": city, 
                          "Lat": city_lat, 
                          "Lng": city_lng, 
                          "Max Temp": city_max_temp-273.15,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass
              
# Indicate that Data Loading is complete 
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | Halifax
Processing Record 2 of Set 1 | Québec
Processing Record 3 of Set 1 | Montréal
Processing Record 4 of Set 1 | Ottawa
Processing Record 5 of Set 1 | Gatineau
Processing Record 6 of Set 1 | Toronto
Processing Record 7 of Set 1 | Hamilton
Processing Record 8 of Set 1 | St. Catharines
Processing Record 9 of Set 1 | Kitchener
Processing Record 10 of Set 1 | London
Processing Record 11 of Set 1 | Windsor
Processing Record 12 of Set 1 | Winnipeg
Processing Record 13 of Set 1 | Calgary
Processing Record 14 of Set 1 | Edmonton
Processing Record 15 of Set 1 | Vancouver
-----------------------------
Data Retrieval Complete
-----------------------------

In [28]:
# Find out how many cities were found
len(city_data)

15

In [29]:
# Convert the cities weather data into a Pandas DataFrame
city_data_df = pd.DataFrame(city_data)

# Show Record Count
city_data_df.count()

City          15
Lat           15
Lng           15
Max Temp      15
Humidity      15
Cloudiness    15
Wind Speed    15
Country       15
Date          15
dtype: int64

In [30]:
# Display sample data
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Halifax,44.6453,-63.5724,-1.00,51,100,3.09,CA,1675988697
1,Québec,46.8123,-71.2145,-4.20,87,100,7.72,CA,1675988330
2,Montréal,45.5088,-73.5878,1.38,94,100,5.66,CA,1675988509
3,Ottawa,45.4112,-75.6981,1.16,94,100,8.23,CA,1675988486
4,Gatineau,45.4772,-75.7016,1.07,93,100,8.23,CA,1675988560
5,Toronto,43.7001,-79.4163,4.06,96,100,8.23,CA,1675988394
6,Hamilton,43.2334,-79.9496,3.74,95,100,4.63,CA,1675988724
7,St. Catharines,43.1668,-79.2496,14.40,100,100,1.54,CA,1675988482
8,Kitchener,43.4254,-80.5112,4.82,100,100,1.54,CA,1675988770
9,London,42.9834,-81.2330,9.57,79,75,10.80,CA,1675988725
10,Windsor,42.3001,-83.0165,8.94,83,100,10.29,CA,1675988453
11,Winnipeg,49.8844,-97.1470,-9.01,48,0,3.60,CA,1675988638
12,Calgary,51.0501,-114.0853,6.97,54,75,2.57,CA,1675988726
13,Edmonton,53.5501,-113.4687,0.44,58,75,2.06,CA,1675988483
14,Vancouver,49.2497,-123.1193,8.18,86,75,5.14,CA,1675988606

In [31]:
city_data_df.index.name = 'City_IDWeather'
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
City_IDWeather,,,,,,,,,
0,Halifax,44.6453,-63.5724,-1.00,51,100,3.09,CA,1675988697
1,Québec,46.8123,-71.2145,-4.20,87,100,7.72,CA,1675988330
2,Montréal,45.5088,-73.5878,1.38,94,100,5.66,CA,1675988509
3,Ottawa,45.4112,-75.6981,1.16,94,100,8.23,CA,1675988486
4,Gatineau,45.4772,-75.7016,1.07,93,100,8.23,CA,1675988560
5,Toronto,43.7001,-79.4163,4.06,96,100,8.23,CA,1675988394
6,Hamilton,43.2334,-79.9496,3.74,95,100,4.63,CA,1675988724
7,St. Catharines,43.1668,-79.2496,14.40,100,100,1.54,CA,1675988482
8,Kitchener,43.4254,-80.5112,4.82,100,100,1.54,CA,1675988770
9,London,42.9834,-81.2330,9.57,79,75,10.80,CA,1675988725
10,Windsor,42.3001,-83.0165,8.94,83,100,10.29,CA,1675988453
11,Winnipeg,49.8844,-97.1470,-9.01,48,0,3.60,CA,1675988638
12,Calgary,51.0501,-114.0853,6.97,54,75,2.57,CA,1675988726
13,Edmonton,53.5501,-113.4687,0.44,58,75,2.06,CA,1675988483
14,Vancouver,49.2497,-123.1193,8.18,86,75,5.14,CA,1675988606

In [39]:
cities_lookup_df = pd.read_csv('Resources/cities_lookup.csv')
#, encoding='ISO-8859-1'

cities_lookup_df

,City_ID,City,City_ID2,GEO,Province,City_IDWeather,Weather_City
0,0,St. John's,18372.0,St. John's,Newfoundland and Labrador [10001],NaN,St. John's
1,1,Halifax,18426.0,Halifax,Nova Scotia [12205],0.0,Halifax
2,2,Québec,18534.0,Québec,Quebec [24421],1.0,Québec
3,3,Sherbrooke,18552.0,Sherbrooke,Quebec [24433],NaN,Sherbrooke
4,4,Montréal,18588.0,Montréal,Quebec [24462],2.0,Montréal
5,5,Ottawa - Gatineau,18642.0,Ottawa-Gatineau,Ontario/Quebec [24505/35505],NaN,NaN
6,6,Ottawa - Gatineau (Quebec part),18606.0,Ottawa-Gatineau,Quebec part [24505],4.0,Gatineau
7,7,Ottawa - Gatineau (Ontario part),18660.0,Ottawa-Gatineau,Ontario part [35505],3.0,Ottawa
8,8,Oshawa,NaN,NaN,NaN,NaN,Oshawa
9,9,Toronto,18732.0,Toronto,Ontario [35535],5.0,Toronto
10,10,Hamilton,18750.0,Hamilton,Ontario [35537],6.0,Hamilton
11,11,St. Catharines - Niagara,18768.0,St.Catharines-Niagara,Ontario [35539],7.0,St. Catharines
12,12,Kitchener - Cambridge - Waterloo,18786.0,Kitchener-Cambridge-Waterloo,Ontario [35541],8.0,Kitchener
13,13,London,18840.0,London,Ontario [35555],9.0,London
14,14,Windsor,18858.0,Windsor,Ontario [35559],10.0,Windsor
15,15,Barrie,18876.0,Barrie,Ontario [35568],NaN,Barrie
16,16,Winnipeg,18948.0,Winnipeg,Manitoba [46602],11.0,Winnipeg
17,17,Regina,18984.0,Regina,Saskatchewan [47705],NaN,Regina
18,18,Saskatoon,19002.0,Saskatoon,Saskatchewan [47725],NaN,Saskatoon
19,19,Calgary,19056.0,Calgary,Alberta [48825],12.0,Calgary
20,20,Edmonton,19074.0,Edmonton,Alberta [48835],13.0,Edmonton
21,21,Kelowna,19110.0,Kelowna,British Columbia [59915],NaN,Kelowna
22,22,Abbotsford - Mission,19128.0,Abbotsford-Mission,British Columbia [59932],NaN,Abbotsford
23,23,Vancouver,19146.0,Vancouver,British Columbia [59933],14.0,Vancouver
24,24,Victoria,19164.0,Victoria,British Columbia [59935],NaN,Victoria

In [40]:
columns_to_keep = ['City_IDWeather', 'GEO', 'City_ID2']
reduced_lookup_df = cities_lookup_df[columns_to_keep]
reduced_lookup_df

    City_IDWeather                           GEO  City_ID2
0              NaN                    St. John's   18372.0
1              0.0                       Halifax   18426.0
2              1.0                        Québec   18534.0
3              NaN                    Sherbrooke   18552.0
4              2.0                      Montréal   18588.0
5              NaN               Ottawa-Gatineau   18642.0
6              4.0               Ottawa-Gatineau   18606.0
7              3.0               Ottawa-Gatineau   18660.0
8              NaN                           NaN       NaN
9              5.0                       Toronto   18732.0
10             6.0                      Hamilton   18750.0
11             7.0         St.Catharines-Niagara   18768.0
12             8.0  Kitchener-Cambridge-Waterloo   18786.0
13             9.0                        London   18840.0
14            10.0                       Windsor   18858.0
15             NaN                        Barrie   18876.0
16            11.0                      Winnipeg   18948.0
17             NaN                        Regina   18984.0
18             NaN                     Saskatoon   19002.0
19            12.0                       Calgary   19056.0
20            13.0                      Edmonton   19074.0
21             NaN                       Kelowna   19110.0
22             NaN            Abbotsford-Mission   19128.0
23            14.0                     Vancouver   19146.0
24             NaN                      Victoria   19164.0

In [41]:
cities_lookup_df1 = reduced_lookup_df.dropna()
cities_lookup_df1

    City_IDWeather                           GEO  City_ID2
1              0.0                       Halifax   18426.0
2              1.0                        Québec   18534.0
4              2.0                      Montréal   18588.0
6              4.0               Ottawa-Gatineau   18606.0
7              3.0               Ottawa-Gatineau   18660.0
9              5.0                       Toronto   18732.0
10             6.0                      Hamilton   18750.0
11             7.0         St.Catharines-Niagara   18768.0
12             8.0  Kitchener-Cambridge-Waterloo   18786.0
13             9.0                        London   18840.0
14            10.0                       Windsor   18858.0
16            11.0                      Winnipeg   18948.0
19            12.0                       Calgary   19056.0
20            13.0                      Edmonton   19074.0
23            14.0                     Vancouver   19146.0

In [42]:
cities_lookup_df2 = cities_lookup_df1.astype({'City_ID2':'int', 'City_IDWeather':'int'})
cities_lookup_df2

    City_IDWeather                           GEO  City_ID2
1                0                       Halifax     18426
2                1                        Québec     18534
4                2                      Montréal     18588
6                4               Ottawa-Gatineau     18606
7                3               Ottawa-Gatineau     18660
9                5                       Toronto     18732
10               6                      Hamilton     18750
11               7         St.Catharines-Niagara     18768
12               8  Kitchener-Cambridge-Waterloo     18786
13               9                        London     18840
14              10                       Windsor     18858
16              11                      Winnipeg     18948
19              12                       Calgary     19056
20              13                      Edmonton     19074
23              14                     Vancouver     19146

In [43]:
merged_df = city_data_df.merge(cities_lookup_df2, on='City_IDWeather', how='inner')
merged_df

,City_IDWeather,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,GEO,City_ID2
0,0,Halifax,44.6453,-63.5724,-1.00,51,100,3.09,CA,1675988697,Halifax,18426
1,1,Québec,46.8123,-71.2145,-4.20,87,100,7.72,CA,1675988330,Québec,18534
2,2,Montréal,45.5088,-73.5878,1.38,94,100,5.66,CA,1675988509,Montréal,18588
3,3,Ottawa,45.4112,-75.6981,1.16,94,100,8.23,CA,1675988486,Ottawa-Gatineau,18660
4,4,Gatineau,45.4772,-75.7016,1.07,93,100,8.23,CA,1675988560,Ottawa-Gatineau,18606
5,5,Toronto,43.7001,-79.4163,4.06,96,100,8.23,CA,1675988394,Toronto,18732
6,6,Hamilton,43.2334,-79.9496,3.74,95,100,4.63,CA,1675988724,Hamilton,18750
7,7,St. Catharines,43.1668,-79.2496,14.40,100,100,1.54,CA,1675988482,St.Catharines-Niagara,18768
8,8,Kitchener,43.4254,-80.5112,4.82,100,100,1.54,CA,1675988770,Kitchener-Cambridge-Waterloo,18786
9,9,London,42.9834,-81.2330,9.57,79,75,10.80,CA,1675988725,London,18840
10,10,Windsor,42.3001,-83.0165,8.94,83,100,10.29,CA,1675988453,Windsor,18858
11,11,Winnipeg,49.8844,-97.1470,-9.01,48,0,3.60,CA,1675988638,Winnipeg,18948
12,12,Calgary,51.0501,-114.0853,6.97,54,75,2.57,CA,1675988726,Calgary,19056
13,13,Edmonton,53.5501,-113.4687,0.44,58,75,2.06,CA,1675988483,Edmonton,19074
14,14,Vancouver,49.2497,-123.1193,8.18,86,75,5.14,CA,1675988606,Vancouver,19146

In [44]:
len(merged_df)

15

In [45]:
# Export the merged_df into a csv

merged_df.to_csv("Resources/weather_data.csv", index_label="City_ID2")