In [95]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

In [96]:
# Impor the OpenWeatherMap API key
from api_keys import weather_api_key

In [97]:
# List of cities
cities = ['Halifax', 'Québec', 'Montréal',
       'Gatineau', 'Ottawa', 'Toronto', 'Hamilton',
       'St. Catharines', 'Kitchener',
       'London', 'Windsor', 'Winnipeg', 'Calgary', 'Edmonton',
       'Vancouver']

In [98]:
# Set the API base URL
url = "http://api.openweathermap.org/data/2.5/weather?q=" 

#https://api.openweathermap.org/data/2.5/weather?q={city name},{country code}&appid={API key}

# Define an empty list to fetch the weather data for each city
city_data = []

# Print to logger
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters
record_count = 1
set_count = 1

# Loop through all the cities in our list to fetch weather data
for i, city in enumerate(cities):
        
    # Group cities in sets of 50 for logging purposes
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 0

    # Create endpoint URL with each city
    #city_url = f"{url}appid={weather_api_key}&q={city}&units=metric"
    city_url = f"{url}{city},CA&appid={weather_api_key}"
        
    # Log the url, record, and set numbers
    print("Processing Record %s of Set %s | %s" % (record_count, set_count, city))

    # Add 1 to the record count
    record_count += 1

    # Run an API request for each of the cities
    try:
        # Parse the JSON and retrieve data
        response_json = requests.get(city_url).json()
        #json.dumps(response_json, indent=4, sort_keys=True)
        #city_weather = response_json["weather"]
        
        # Parse out latitude, longitude, max temp, humidity, cloudiness, wind speed, country, and date
        city_lat = response_json["coord"]["lat"]
        city_lng = response_json["coord"]["lon"]
        city_max_temp = response_json["main"]["temp_max"]
        city_humidity = response_json["main"]["humidity"]
        city_clouds = response_json["clouds"]["all"]
        city_wind = response_json["wind"]["speed"]
        city_country = response_json["sys"]["country"]
        city_date = response_json["dt"]
      

        # Append the City information into city_data list
        city_data.append({"City": city, 
                          "Lat": city_lat, 
                          "Lng": city_lng, 
                          "Max Temp": city_max_temp-273.15,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass
              
# Indicate that Data Loading is complete 
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | Halifax
Processing Record 2 of Set 1 | Québec
Processing Record 3 of Set 1 | Montréal
Processing Record 4 of Set 1 | Gatineau
Processing Record 5 of Set 1 | Ottawa
Processing Record 6 of Set 1 | Toronto
Processing Record 7 of Set 1 | Hamilton
Processing Record 8 of Set 1 | St. Catharines
Processing Record 9 of Set 1 | Kitchener
Processing Record 10 of Set 1 | London
Processing Record 11 of Set 1 | Windsor
Processing Record 12 of Set 1 | Winnipeg
Processing Record 13 of Set 1 | Calgary
Processing Record 14 of Set 1 | Edmonton
Processing Record 15 of Set 1 | Vancouver
-----------------------------
Data Retrieval Complete
-----------------------------

In [99]:
# Find out how many cities were found
len(city_data)

15

In [100]:
# Convert the cities weather data into a Pandas DataFrame
city_data_df = pd.DataFrame(city_data)

# Show Record Count
city_data_df.count()

City          15
Lat           15
Lng           15
Max Temp      15
Humidity      15
Cloudiness    15
Wind Speed    15
Country       15
Date          15
dtype: int64

In [101]:
# Display sample data
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Halifax,44.6453,-63.5724,-1.00,68,100,3.09,CA,1676008561
1,Québec,46.8123,-71.2145,-1.07,93,100,11.32,CA,1676008650
2,Montréal,45.5088,-73.5878,4.08,96,100,5.14,CA,1676008669
3,Gatineau,45.4772,-75.7016,1.62,92,100,3.09,CA,1676008557
4,Ottawa,45.4112,-75.6981,1.48,94,100,3.09,CA,1676008630
5,Toronto,43.7001,-79.4163,6.22,88,100,10.80,CA,1676008452
6,Hamilton,43.2334,-79.9496,5.10,84,100,12.86,CA,1676008530
7,St. Catharines,43.1668,-79.2496,5.84,80,98,10.80,CA,1676008785
8,Kitchener,43.4254,-80.5112,3.57,92,75,10.29,CA,1676008678
9,London,42.9834,-81.2330,4.18,83,100,9.26,CA,1676008773
10,Windsor,42.3001,-83.0165,4.18,90,100,9.26,CA,1676008786
11,Winnipeg,49.8844,-97.1470,-12.01,77,0,2.57,CA,1676008502
12,Calgary,51.0501,-114.0853,3.20,65,75,5.66,CA,1676008599
13,Edmonton,53.5501,-113.4687,1.25,64,78,2.06,CA,1676008627
14,Vancouver,49.2497,-123.1193,9.86,79,75,7.20,CA,1676008627

In [102]:
city_data_df.index.name = 'City_IDWeather'
city_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
City_IDWeather,,,,,,,,,
0,Halifax,44.6453,-63.5724,-1.00,68,100,3.09,CA,1676008561
1,Québec,46.8123,-71.2145,-1.07,93,100,11.32,CA,1676008650
2,Montréal,45.5088,-73.5878,4.08,96,100,5.14,CA,1676008669
3,Gatineau,45.4772,-75.7016,1.62,92,100,3.09,CA,1676008557
4,Ottawa,45.4112,-75.6981,1.48,94,100,3.09,CA,1676008630
5,Toronto,43.7001,-79.4163,6.22,88,100,10.80,CA,1676008452
6,Hamilton,43.2334,-79.9496,5.10,84,100,12.86,CA,1676008530
7,St. Catharines,43.1668,-79.2496,5.84,80,98,10.80,CA,1676008785
8,Kitchener,43.4254,-80.5112,3.57,92,75,10.29,CA,1676008678
9,London,42.9834,-81.2330,4.18,83,100,9.26,CA,1676008773
10,Windsor,42.3001,-83.0165,4.18,90,100,9.26,CA,1676008786
11,Winnipeg,49.8844,-97.1470,-12.01,77,0,2.57,CA,1676008502
12,Calgary,51.0501,-114.0853,3.20,65,75,5.66,CA,1676008599
13,Edmonton,53.5501,-113.4687,1.25,64,78,2.06,CA,1676008627
14,Vancouver,49.2497,-123.1193,9.86,79,75,7.20,CA,1676008627

In [103]:
cities_lookup_df = pd.read_csv('Resources/cities_lookup.csv')
#, encoding='ISO-8859-1'

cities_lookup_df

,City_ID,City,City_ID2,GEO,Province,City_IDWeather,Weather_City
0,0,Halifax,18426,Halifax,Nova Scotia [12205],0,Halifax
1,1,Québec,18534,Québec,Quebec [24421],1,Québec
2,2,Montréal,18588,Montréal,Quebec [24462],2,Montréal
3,3,Ottawa - Gatineau (Quebec part),18606,Ottawa-Gatineau,Quebec part [24505],4,Gatineau
4,4,Ottawa - Gatineau (Ontario part),18660,Ottawa-Gatineau,Ontario part [35505],3,Ottawa
5,5,Toronto,18732,Toronto,Ontario [35535],5,Toronto
6,6,Hamilton,18750,Hamilton,Ontario [35537],6,Hamilton
7,7,St. Catharines - Niagara,18768,St.Catharines-Niagara,Ontario [35539],7,St. Catharines
8,8,Kitchener - Cambridge - Waterloo,18786,Kitchener-Cambridge-Waterloo,Ontario [35541],8,Kitchener
9,9,London,18840,London,Ontario [35555],9,London
10,10,Windsor,18858,Windsor,Ontario [35559],10,Windsor
11,11,Winnipeg,18948,Winnipeg,Manitoba [46602],11,Winnipeg
12,12,Calgary,19056,Calgary,Alberta [48825],12,Calgary
13,13,Edmonton,19074,Edmonton,Alberta [48835],13,Edmonton
14,14,Vancouver,19146,Vancouver,British Columbia [59933],14,Vancouver

In [104]:
columns_to_keep = ['City_IDWeather', 'GEO', 'City_ID2']
reduced_lookup_df = cities_lookup_df[columns_to_keep]
reduced_lookup_df

    City_IDWeather                           GEO  City_ID2
0                0                       Halifax     18426
1                1                        Québec     18534
2                2                      Montréal     18588
3                4               Ottawa-Gatineau     18606
4                3               Ottawa-Gatineau     18660
5                5                       Toronto     18732
6                6                      Hamilton     18750
7                7         St.Catharines-Niagara     18768
8                8  Kitchener-Cambridge-Waterloo     18786
9                9                        London     18840
10              10                       Windsor     18858
11              11                      Winnipeg     18948
12              12                       Calgary     19056
13              13                      Edmonton     19074
14              14                     Vancouver     19146

In [105]:
cities_lookup_df1 = reduced_lookup_df.dropna()
cities_lookup_df1

    City_IDWeather                           GEO  City_ID2
0                0                       Halifax     18426
1                1                        Québec     18534
2                2                      Montréal     18588
3                4               Ottawa-Gatineau     18606
4                3               Ottawa-Gatineau     18660
5                5                       Toronto     18732
6                6                      Hamilton     18750
7                7         St.Catharines-Niagara     18768
8                8  Kitchener-Cambridge-Waterloo     18786
9                9                        London     18840
10              10                       Windsor     18858
11              11                      Winnipeg     18948
12              12                       Calgary     19056
13              13                      Edmonton     19074
14              14                     Vancouver     19146

In [106]:
cities_lookup_df2 = cities_lookup_df1.astype({'City_ID2':'int', 'City_IDWeather':'int'})
cities_lookup_df2

    City_IDWeather                           GEO  City_ID2
0                0                       Halifax     18426
1                1                        Québec     18534
2                2                      Montréal     18588
3                4               Ottawa-Gatineau     18606
4                3               Ottawa-Gatineau     18660
5                5                       Toronto     18732
6                6                      Hamilton     18750
7                7         St.Catharines-Niagara     18768
8                8  Kitchener-Cambridge-Waterloo     18786
9                9                        London     18840
10              10                       Windsor     18858
11              11                      Winnipeg     18948
12              12                       Calgary     19056
13              13                      Edmonton     19074
14              14                     Vancouver     19146

In [107]:
# Merge the dataframes to add the other names for the city to merge later
merged_df = city_data_df.merge(cities_lookup_df2, on='City_IDWeather', how='inner')
merged_df

,City_IDWeather,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,GEO,City_ID2
0,0,Halifax,44.6453,-63.5724,-1.00,68,100,3.09,CA,1676008561,Halifax,18426
1,1,Québec,46.8123,-71.2145,-1.07,93,100,11.32,CA,1676008650,Québec,18534
2,2,Montréal,45.5088,-73.5878,4.08,96,100,5.14,CA,1676008669,Montréal,18588
3,3,Gatineau,45.4772,-75.7016,1.62,92,100,3.09,CA,1676008557,Ottawa-Gatineau,18660
4,4,Ottawa,45.4112,-75.6981,1.48,94,100,3.09,CA,1676008630,Ottawa-Gatineau,18606
5,5,Toronto,43.7001,-79.4163,6.22,88,100,10.80,CA,1676008452,Toronto,18732
6,6,Hamilton,43.2334,-79.9496,5.10,84,100,12.86,CA,1676008530,Hamilton,18750
7,7,St. Catharines,43.1668,-79.2496,5.84,80,98,10.80,CA,1676008785,St.Catharines-Niagara,18768
8,8,Kitchener,43.4254,-80.5112,3.57,92,75,10.29,CA,1676008678,Kitchener-Cambridge-Waterloo,18786
9,9,London,42.9834,-81.2330,4.18,83,100,9.26,CA,1676008773,London,18840
10,10,Windsor,42.3001,-83.0165,4.18,90,100,9.26,CA,1676008786,Windsor,18858
11,11,Winnipeg,49.8844,-97.1470,-12.01,77,0,2.57,CA,1676008502,Winnipeg,18948
12,12,Calgary,51.0501,-114.0853,3.20,65,75,5.66,CA,1676008599,Calgary,19056
13,13,Edmonton,53.5501,-113.4687,1.25,64,78,2.06,CA,1676008627,Edmonton,19074
14,14,Vancouver,49.2497,-123.1193,9.86,79,75,7.20,CA,1676008627,Vancouver,19146

In [108]:
# Reduce the number of columns
columns_to_keep1 = ['Wind Speed', 'Max Temp', 'City_ID2', 'City']
weather_df = merged_df[columns_to_keep1]
weather_df

    Wind Speed  Max Temp  City_ID2            City
0         3.09     -1.00     18426         Halifax
1        11.32     -1.07     18534          Québec
2         5.14      4.08     18588        Montréal
3         3.09      1.62     18660        Gatineau
4         3.09      1.48     18606          Ottawa
5        10.80      6.22     18732         Toronto
6        12.86      5.10     18750        Hamilton
7        10.80      5.84     18768  St. Catharines
8        10.29      3.57     18786       Kitchener
9         9.26      4.18     18840          London
10        9.26      4.18     18858         Windsor
11        2.57    -12.01     18948        Winnipeg
12        5.66      3.20     19056         Calgary
13        2.06      1.25     19074        Edmonton
14        7.20      9.86     19146       Vancouver

In [109]:
len(weather_df)

15

In [110]:
# Export the weather data into a csv
weather_df.to_csv("Output/weather_data.csv", index_label="City_ID2")