In [1]:
import os
import pandas as pd

In [34]:
bc_string = 'Resources/BC_Cultural_Participation.csv'
bc_df = pd.read_csv(bc_string)
bc_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,British Columbia,2016A000259,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,635.0,thousands,3,v119724632,13.1.1.1.1.1.1,635.0,NaN,NaN,NaN,0
1,2016,British Columbia,2016A000259,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,15.8,units,0,v119724633,13.1.1.1.1.1.2,15.8,NaN,NaN,NaN,1
2,2016,British Columbia,2016A000259,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119724636,13.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,British Columbia,2016A000259,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119724637,13.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,British Columbia,2016A000259,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,183.0,thousands,3,v119724640,13.1.1.1.1.3.1,183.0,E,NaN,NaN,0

In [35]:
bc_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
bc_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
bc_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,British Columbia,Making music,Number of persons,Persons,635.0,thousands,3
1,British Columbia,Making music,Percentage of persons,Percent,15.8,units,0
2,British Columbia,Theatre,Number of persons,Persons,0.0,thousands,3
3,British Columbia,Theatre,Percentage of persons,Percent,0.0,units,0
4,British Columbia,Audio-visual and interactive media,Number of persons,Persons,183.0,thousands,3
5,British Columbia,Audio-visual and interactive media,Percentage of persons,Percent,4.5,units,0
6,British Columbia,Dancing,Number of persons,Persons,394.0,thousands,3
7,British Columbia,Dancing,Percentage of persons,Percent,9.8,units,0
8,British Columbia,Visual arts,Number of persons,Persons,594.0,thousands,3
9,British Columbia,Visual arts,Percentage of persons,Percent,14.8,units,0
10,British Columbia,Crafting,Number of persons,Persons,744.0,thousands,3
11,British Columbia,Crafting,Percentage of persons,Percent,18.5,units,0
12,British Columbia,Writing,Number of persons,Persons,478.0,thousands,3
13,British Columbia,Writing,Percentage of persons,Percent,11.9,units,0
14,British Columbia,Other cultural activities,Number of persons,Persons,203.0,thousands,3
15,British Columbia,Other cultural activities,Percentage of persons,Percent,5.0,units,0
16,British Columbia,Did not participate in cultural activities,Number of persons,Persons,1831.0,thousands,3
17,British Columbia,Did not participate in cultural activities,Percentage of persons,Percent,45.5,units,0

In [39]:
mb_string = 'Resources/MB_Cultural_Participation.csv'
mb_df = pd.read_csv(mb_string)
mb_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Manitoba,2016A000011124,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,181.0,thousands,3,v119258072,1.1.1.1.1.1.1,4374.0,NaN,NaN,NaN,0
1,2016,Manitoba,2016A000011124,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,17.2,units,0,v119258073,1.1.1.1.1.1.2,14.5,NaN,NaN,NaN,1
2,2016,Manitoba,2016A000011124,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119258076,1.1.1.1.1.2.1,415.0,NaN,NaN,NaN,0
3,2016,Manitoba,2016A000011124,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119258077,1.1.1.1.1.2.2,1.4,NaN,NaN,NaN,1
4,2016,Manitoba,2016A000011124,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,0.0,thousands,3,v119258080,1.1.1.1.1.3.1,1240.0,NaN,NaN,NaN,0

In [40]:
mb_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
mb_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
mb_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Manitoba,Making music,Number of persons,Persons,181.0,thousands,3
1,Manitoba,Making music,Percentage of persons,Percent,17.2,units,0
2,Manitoba,Theatre,Number of persons,Persons,0.0,thousands,3
3,Manitoba,Theatre,Percentage of persons,Percent,0.0,units,0
4,Manitoba,Audio-visual and interactive media,Number of persons,Persons,0.0,thousands,3
5,Manitoba,Audio-visual and interactive media,Percentage of persons,Percent,0.0,units,0
6,Manitoba,Dancing,Number of persons,Persons,78.0,thousands,3
7,Manitoba,Dancing,Percentage of persons,Percent,7.4,units,0
8,Manitoba,Visual arts,Number of persons,Persons,120.0,thousands,3
9,Manitoba,Visual arts,Percentage of persons,Percent,11.4,units,0
10,Manitoba,Crafting,Number of persons,Persons,197.0,thousands,3
11,Manitoba,Crafting,Percentage of persons,Percent,18.6,units,0
12,Manitoba,Writing,Number of persons,Persons,93.0,thousands,3
13,Manitoba,Writing,Percentage of persons,Percent,8.8,units,0
14,Manitoba,Other cultural activities,Number of persons,Persons,68.0,thousands,3
15,Manitoba,Other cultural activities,Percentage of persons,Percent,6.4,units,0
16,Manitoba,Did not participate in cultural activities,Number of persons,Persons,500.0,thousands,3
17,Manitoba,Did not participate in cultural activities,Percentage of persons,Percent,47.3,units,0

In [32]:
nb_string = 'Resources/NB_Cultural_Participation.csv'
nb_df = pd.read_csv(nb_string)
nb_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,New Brunswick,2016A000213,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,94.0,thousands,3,v119452472,6.1.1.1.1.1.1,94.0,NaN,NaN,NaN,0
1,2016,New Brunswick,2016A000213,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,14.8,units,0,v119452473,6.1.1.1.1.1.2,14.8,NaN,NaN,NaN,1
2,2016,New Brunswick,2016A000213,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119452476,6.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,New Brunswick,2016A000213,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119452477,6.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,New Brunswick,2016A000213,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,20.0,thousands,3,v119452480,6.1.1.1.1.3.1,20.0,E,NaN,NaN,0

In [33]:
nb_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
nb_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
nb_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,New Brunswick,Making music,Number of persons,Persons,94.0,thousands,3
1,New Brunswick,Making music,Percentage of persons,Percent,14.8,units,0
2,New Brunswick,Theatre,Number of persons,Persons,0.0,thousands,3
3,New Brunswick,Theatre,Percentage of persons,Percent,0.0,units,0
4,New Brunswick,Audio-visual and interactive media,Number of persons,Persons,20.0,thousands,3
5,New Brunswick,Audio-visual and interactive media,Percentage of persons,Percent,3.1,units,0
6,New Brunswick,Dancing,Number of persons,Persons,53.0,thousands,3
7,New Brunswick,Dancing,Percentage of persons,Percent,8.3,units,0
8,New Brunswick,Visual arts,Number of persons,Persons,74.0,thousands,3
9,New Brunswick,Visual arts,Percentage of persons,Percent,11.7,units,0
10,New Brunswick,Crafting,Number of persons,Persons,142.0,thousands,3
11,New Brunswick,Crafting,Percentage of persons,Percent,22.4,units,0
12,New Brunswick,Writing,Number of persons,Persons,36.0,thousands,3
13,New Brunswick,Writing,Percentage of persons,Percent,5.7,units,0
14,New Brunswick,Other cultural activities,Number of persons,Persons,42.0,thousands,3
15,New Brunswick,Other cultural activities,Percentage of persons,Percent,6.7,units,0
16,New Brunswick,Did not participate in cultural activities,Number of persons,Persons,293.0,thousands,3
17,New Brunswick,Did not participate in cultural activities,Percentage of persons,Percent,46.1,units,0

In [41]:
nl_string = 'Resources/NL_Cultural_Participation.csv'
nl_df = pd.read_csv(nl_string)
nl_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Newfoundland and Labrador,2016A000210,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,76.0,thousands,3,v119335832,3.1.1.1.1.1.1,76.0,NaN,NaN,NaN,0
1,2016,Newfoundland and Labrador,2016A000210,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,17.1,units,0,v119335833,3.1.1.1.1.1.2,17.1,NaN,NaN,NaN,1
2,2016,Newfoundland and Labrador,2016A000210,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119335836,3.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,Newfoundland and Labrador,2016A000210,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119335837,3.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,Newfoundland and Labrador,2016A000210,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,0.0,thousands,3,v119335840,3.1.1.1.1.3.1,NaN,F,NaN,NaN,0

In [42]:
nl_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
nl_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
nl_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Newfoundland and Labrador,Making music,Number of persons,Persons,76.0,thousands,3
1,Newfoundland and Labrador,Making music,Percentage of persons,Percent,17.1,units,0
2,Newfoundland and Labrador,Theatre,Number of persons,Persons,0.0,thousands,3
3,Newfoundland and Labrador,Theatre,Percentage of persons,Percent,0.0,units,0
4,Newfoundland and Labrador,Audio-visual and interactive media,Number of persons,Persons,0.0,thousands,3
5,Newfoundland and Labrador,Audio-visual and interactive media,Percentage of persons,Percent,0.0,units,0
6,Newfoundland and Labrador,Dancing,Number of persons,Persons,61.0,thousands,3
7,Newfoundland and Labrador,Dancing,Percentage of persons,Percent,13.6,units,0
8,Newfoundland and Labrador,Visual arts,Number of persons,Persons,39.0,thousands,3
9,Newfoundland and Labrador,Visual arts,Percentage of persons,Percent,8.8,units,0
10,Newfoundland and Labrador,Crafting,Number of persons,Persons,97.0,thousands,3
11,Newfoundland and Labrador,Crafting,Percentage of persons,Percent,21.6,units,0
12,Newfoundland and Labrador,Writing,Number of persons,Persons,30.0,thousands,3
13,Newfoundland and Labrador,Writing,Percentage of persons,Percent,6.7,units,0
14,Newfoundland and Labrador,Other cultural activities,Number of persons,Persons,25.0,thousands,3
15,Newfoundland and Labrador,Other cultural activities,Percentage of persons,Percent,5.6,units,0
16,Newfoundland and Labrador,Did not participate in cultural activities,Number of persons,Persons,191.0,thousands,3
17,Newfoundland and Labrador,Did not participate in cultural activities,Percentage of persons,Percent,42.6,units,0

In [43]:
ab_string = 'Resources/AB_Cultural_Participation.csv'
ab_df = pd.read_csv(ab_string)
ab_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Alberta,2016A000248,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,427.0,thousands,3,v119685752,12.1.1.1.1.1.1,427.0,NaN,NaN,NaN,0
1,2016,Alberta,2016A000248,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,12.3,units,0,v119685753,12.1.1.1.1.1.2,12.3,NaN,NaN,NaN,1
2,2016,Alberta,2016A000248,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119685756,12.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,Alberta,2016A000248,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119685757,12.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,Alberta,2016A000248,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,140.0,thousands,3,v119685760,12.1.1.1.1.3.1,140.0,E,NaN,NaN,0

In [44]:
ab_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
ab_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
ab_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Alberta,Making music,Number of persons,Persons,427.0,thousands,3
1,Alberta,Making music,Percentage of persons,Percent,12.3,units,0
2,Alberta,Theatre,Number of persons,Persons,0.0,thousands,3
3,Alberta,Theatre,Percentage of persons,Percent,0.0,units,0
4,Alberta,Audio-visual and interactive media,Number of persons,Persons,140.0,thousands,3
5,Alberta,Audio-visual and interactive media,Percentage of persons,Percent,4.0,units,0
6,Alberta,Dancing,Number of persons,Persons,353.0,thousands,3
7,Alberta,Dancing,Percentage of persons,Percent,10.2,units,0
8,Alberta,Visual arts,Number of persons,Persons,467.0,thousands,3
9,Alberta,Visual arts,Percentage of persons,Percent,13.5,units,0
10,Alberta,Crafting,Number of persons,Persons,667.0,thousands,3
11,Alberta,Crafting,Percentage of persons,Percent,19.3,units,0
12,Alberta,Writing,Number of persons,Persons,404.0,thousands,3
13,Alberta,Writing,Percentage of persons,Percent,11.7,units,0
14,Alberta,Other cultural activities,Number of persons,Persons,144.0,thousands,3
15,Alberta,Other cultural activities,Percentage of persons,Percent,4.2,units,0
16,Alberta,Did not participate in cultural activities,Number of persons,Persons,1653.0,thousands,3
17,Alberta,Did not participate in cultural activities,Percentage of persons,Percent,47.8,units,0

In [45]:
ns_string = 'Resources/NS_Cultural_Participation.csv'
ns_df = pd.read_csv(ns_string)
ns_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Nova Scotia,2016A000212,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,144.0,thousands,3,v119413592,5.1.1.1.1.1.1,144.0,NaN,NaN,NaN,0
1,2016,Nova Scotia,2016A000212,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,17.9,units,0,v119413593,5.1.1.1.1.1.2,17.9,NaN,NaN,NaN,1
2,2016,Nova Scotia,2016A000212,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119413596,5.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,Nova Scotia,2016A000212,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119413597,5.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,Nova Scotia,2016A000212,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,35.0,thousands,3,v119413600,5.1.1.1.1.3.1,35.0,E,NaN,NaN,0

In [46]:
ns_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
ns_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
ns_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Nova Scotia,Making music,Number of persons,Persons,144.0,thousands,3
1,Nova Scotia,Making music,Percentage of persons,Percent,17.9,units,0
2,Nova Scotia,Theatre,Number of persons,Persons,0.0,thousands,3
3,Nova Scotia,Theatre,Percentage of persons,Percent,0.0,units,0
4,Nova Scotia,Audio-visual and interactive media,Number of persons,Persons,35.0,thousands,3
5,Nova Scotia,Audio-visual and interactive media,Percentage of persons,Percent,4.3,units,0
6,Nova Scotia,Dancing,Number of persons,Persons,62.0,thousands,3
7,Nova Scotia,Dancing,Percentage of persons,Percent,7.7,units,0
8,Nova Scotia,Visual arts,Number of persons,Persons,121.0,thousands,3
9,Nova Scotia,Visual arts,Percentage of persons,Percent,15.0,units,0
10,Nova Scotia,Crafting,Number of persons,Persons,186.0,thousands,3
11,Nova Scotia,Crafting,Percentage of persons,Percent,23.2,units,0
12,Nova Scotia,Writing,Number of persons,Persons,84.0,thousands,3
13,Nova Scotia,Writing,Percentage of persons,Percent,10.4,units,0
14,Nova Scotia,Other cultural activities,Number of persons,Persons,68.0,thousands,3
15,Nova Scotia,Other cultural activities,Percentage of persons,Percent,8.5,units,0
16,Nova Scotia,Did not participate in cultural activities,Number of persons,Persons,315.0,thousands,3
17,Nova Scotia,Did not participate in cultural activities,Percentage of persons,Percent,39.1,units,0

In [47]:
on_string = 'Resources/ON_Cultural_Participation.csv'
on_df = pd.read_csv(on_string)
on_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Ontario,2016A000235,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,1847.0,thousands,3,v119530232,8.1.1.1.1.1.1,1847.0,NaN,NaN,NaN,0
1,2016,Ontario,2016A000235,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,15.8,units,0,v119530233,8.1.1.1.1.1.2,15.8,NaN,NaN,NaN,1
2,2016,Ontario,2016A000235,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,217.0,thousands,3,v119530236,8.1.1.1.1.2.1,217.0,E,NaN,NaN,0
3,2016,Ontario,2016A000235,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,1.9,units,0,v119530237,8.1.1.1.1.2.2,1.9,E,NaN,NaN,1
4,2016,Ontario,2016A000235,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,624.0,thousands,3,v119530240,8.1.1.1.1.3.1,624.0,NaN,NaN,NaN,0

In [48]:
on_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
on_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
on_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Ontario,Making music,Number of persons,Persons,1847.0,thousands,3
1,Ontario,Making music,Percentage of persons,Percent,15.8,units,0
2,Ontario,Theatre,Number of persons,Persons,217.0,thousands,3
3,Ontario,Theatre,Percentage of persons,Percent,1.9,units,0
4,Ontario,Audio-visual and interactive media,Number of persons,Persons,624.0,thousands,3
5,Ontario,Audio-visual and interactive media,Percentage of persons,Percent,5.4,units,0
6,Ontario,Dancing,Number of persons,Persons,1181.0,thousands,3
7,Ontario,Dancing,Percentage of persons,Percent,10.1,units,0
8,Ontario,Visual arts,Number of persons,Persons,1736.0,thousands,3
9,Ontario,Visual arts,Percentage of persons,Percent,14.9,units,0
10,Ontario,Crafting,Number of persons,Persons,2257.0,thousands,3
11,Ontario,Crafting,Percentage of persons,Percent,19.4,units,0
12,Ontario,Writing,Number of persons,Persons,1516.0,thousands,3
13,Ontario,Writing,Percentage of persons,Percent,13.0,units,0
14,Ontario,Other cultural activities,Number of persons,Persons,692.0,thousands,3
15,Ontario,Other cultural activities,Percentage of persons,Percent,5.9,units,0
16,Ontario,Did not participate in cultural activities,Number of persons,Persons,5266.0,thousands,3
17,Ontario,Did not participate in cultural activities,Percentage of persons,Percent,45.2,units,0

In [49]:
pe_string = 'Resources/PE_Cultural_Participation.csv'
pe_df = pd.read_csv(pe_string)
pe_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Prince Edward Island,2016A000211,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,22.0,thousands,3,v119374712,4.1.1.1.1.1.1,22.0,NaN,NaN,NaN,0
1,2016,Prince Edward Island,2016A000211,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,17.7,units,0,v119374713,4.1.1.1.1.1.2,17.7,NaN,NaN,NaN,1
2,2016,Prince Edward Island,2016A000211,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119374716,4.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,Prince Edward Island,2016A000211,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119374717,4.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,Prince Edward Island,2016A000211,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,0.0,thousands,3,v119374720,4.1.1.1.1.3.1,NaN,F,NaN,NaN,0

In [50]:
pe_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
pe_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
pe_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Prince Edward Island,Making music,Number of persons,Persons,22.0,thousands,3
1,Prince Edward Island,Making music,Percentage of persons,Percent,17.7,units,0
2,Prince Edward Island,Theatre,Number of persons,Persons,0.0,thousands,3
3,Prince Edward Island,Theatre,Percentage of persons,Percent,0.0,units,0
4,Prince Edward Island,Audio-visual and interactive media,Number of persons,Persons,0.0,thousands,3
5,Prince Edward Island,Audio-visual and interactive media,Percentage of persons,Percent,0.0,units,0
6,Prince Edward Island,Dancing,Number of persons,Persons,8.0,thousands,3
7,Prince Edward Island,Dancing,Percentage of persons,Percent,6.8,units,0
8,Prince Edward Island,Visual arts,Number of persons,Persons,18.0,thousands,3
9,Prince Edward Island,Visual arts,Percentage of persons,Percent,15.0,units,0
10,Prince Edward Island,Crafting,Number of persons,Persons,32.0,thousands,3
11,Prince Edward Island,Crafting,Percentage of persons,Percent,25.8,units,0
12,Prince Edward Island,Writing,Number of persons,Persons,11.0,thousands,3
13,Prince Edward Island,Writing,Percentage of persons,Percent,9.4,units,0
14,Prince Edward Island,Other cultural activities,Number of persons,Persons,10.0,thousands,3
15,Prince Edward Island,Other cultural activities,Percentage of persons,Percent,8.0,units,0
16,Prince Edward Island,Did not participate in cultural activities,Number of persons,Persons,48.0,thousands,3
17,Prince Edward Island,Did not participate in cultural activities,Percentage of persons,Percent,39.0,units,0

In [51]:
qc_string = 'Resources/QC_Cultural_Participation.csv'
qc_df = pd.read_csv(qc_string)
qc_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Current employment status,Perceived health,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016,Quebec,2016A000224,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Number of persons,Persons,807.0,thousands,3,v119491352,7.1.1.1.1.1.1,807.0,NaN,NaN,NaN,0
1,2016,Quebec,2016A000224,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Making music,Percentage of persons,Percent,11.6,units,0,v119491353,7.1.1.1.1.1.2,11.6,NaN,NaN,NaN,1
2,2016,Quebec,2016A000224,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Number of persons,Persons,0.0,thousands,3,v119491356,7.1.1.1.1.2.1,NaN,F,NaN,NaN,0
3,2016,Quebec,2016A000224,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Theatre,Percentage of persons,Percent,0.0,units,0,v119491357,7.1.1.1.1.2.2,NaN,F,NaN,NaN,1
4,2016,Quebec,2016A000224,"Total, 15 years and over",Both sexes,"Total, current employment status","Total, perceived health",Audio-visual and interactive media,Number of persons,Persons,183.0,thousands,3,v119491360,7.1.1.1.1.3.1,183.0,E,NaN,NaN,0

In [52]:
qc_df.drop(columns=["REF_DATE","DGUID","Age group","Sex","Current employment status", "Perceived health", "VECTOR", "COORDINATE"], inplace=True)
qc_df.drop(columns=["VALUE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"], inplace=True)
qc_df

,GEO,Cultural activities,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID
0,Quebec,Making music,Number of persons,Persons,807.0,thousands,3
1,Quebec,Making music,Percentage of persons,Percent,11.6,units,0
2,Quebec,Theatre,Number of persons,Persons,0.0,thousands,3
3,Quebec,Theatre,Percentage of persons,Percent,0.0,units,0
4,Quebec,Audio-visual and interactive media,Number of persons,Persons,183.0,thousands,3
5,Quebec,Audio-visual and interactive media,Percentage of persons,Percent,2.6,units,0
6,Quebec,Dancing,Number of persons,Persons,491.0,thousands,3
7,Quebec,Dancing,Percentage of persons,Percent,7.1,units,0
8,Quebec,Visual arts,Number of persons,Persons,589.0,thousands,3
9,Quebec,Visual arts,Percentage of persons,Percent,8.5,units,0
10,Quebec,Crafting,Number of persons,Persons,781.0,thousands,3
11,Quebec,Crafting,Percentage of persons,Percent,11.2,units,0
12,Quebec,Writing,Number of persons,Persons,517.0,thousands,3
13,Quebec,Writing,Percentage of persons,Percent,7.4,units,0
14,Quebec,Other cultural activities,Number of persons,Persons,254.0,thousands,3
15,Quebec,Other cultural activities,Percentage of persons,Percent,3.6,units,0
16,Quebec,Did not participate in cultural activities,Number of persons,Persons,4153.0,thousands,3
17,Quebec,Did not participate in cultural activities,Percentage of persons,Percent,59.7,units,0